kind: Secret
apiVersion: v1
metadata:
  name: backend-secret
data:
  username: dGVzdHVzZXI=
  password: dGVzdHBhc3N3b3Jk
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/google-containers/nginx-slim:0.8
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        secret:
          secretName: backend-secret
          defaultMode: 0666
