kind: Secret
apiVersion: v1
metadata:
  name: mysql
data:
  password: bXlzcWxwYXNzd29yZA==
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        image: mysql:5.6.36
        ports:
        - containerPort: 3306
