kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: echoserver
spec:
  replicas: 3
  selector:
    matchLabels: &labels
      app: echoserver
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google-containers/echoserver:1.6
        ports:
        - containerPort: 8080
